// PROTOTYPE DATA — in-memory only, wiped on reload. Stands in for Supabase.

export const WATERSHED_GROUPS = [
  { id: 'lima-viana', name: 'Lima — Viana do Castelo' },
  { id: 'neiva', name: 'Neiva' },
  { id: 'coura', name: 'Coura' },
]

export const DEFAULT_WATERSHED_ID = 'lima-viana'

export const SOURCE_TYPES = [
  'Mina (mine)',
  'Dug well',
  'Borehole',
  'Spring',
  'Shared reservoir',
  'Private reservoir',
]

export const DEFAULT_QUALITY_MEASURES = [
  { id: 'ph', name: 'pH', scale: '0–14, every 0.5' },
  { id: 'nitrite', name: 'Nitrite as NO₂-N', scale: '0 / 0.5 / 1 / 5 / 10 ppm' },
  { id: 'nitrate', name: 'Nitrate as NO₃-N', scale: '0 / 5 / 10 / 25 / 50 ppm' },
]

// A couple of seeded samples + one past session, so filters and the map
// have something to work with before the user adds anything themselves.
export const SEED_SESSIONS = [
  { id: 'session-seed-1', label: 'Field day — 12 Jul' },
  { id: 'session-mock-1', label: 'Spring check — 18 Mar 2026' },
  { id: 'session-mock-0', label: 'Autumn walk — 2 Nov 2025' },
]

export const SEED_SAMPLES = [
  {
    id: 'seed-1',
    sessionId: 'session-seed-1',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.706, -8.79],
    sourceType: 'Dug well',
    readings: [{ measureId: 'nitrate', value: '25' }, { measureId: 'ph', value: '5.5' }],
    hazards: ['septic', 'agriculture'],
    createdAt: '2026-07-12T10:15:00Z',
  },
  {
    id: 'seed-2',
    sessionId: 'session-seed-1',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.685, -8.815],
    sourceType: 'Spring',
    readings: [{ measureId: 'nitrate', value: '0' }, { measureId: 'ph', value: '7' }],
    hazards: [],
    createdAt: '2026-07-12T11:02:00Z',
  },
  {
    id: 'seed-3',
    sessionId: 'session-seed-1',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-lima-lower',
    position: [41.72, -8.83],
    sourceType: 'Borehole',
    readings: [{ measureId: 'ph', value: '6.5' }],
    hazards: [],
    createdAt: '2026-07-12T11:40:00Z',
  },
  {
    id: 'seed-4',
    sessionId: 'session-seed-1',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.698, -8.802],
    sourceType: 'Mina (mine)',
    readings: [{ measureId: 'nitrate', value: '10' }],
    hazards: [],
    createdAt: '2026-07-12T12:10:00Z',
  },
  {
    id: 'seed-5',
    sessionId: 'session-seed-1',
    watershedId: 'lima-viana',
    catchmentId: '2121213570',
    position: [41.6236, -8.4912],
    sourceType: 'Spring',
    readings: [{ measureId: 'nitrate', value: '10' }, { measureId: 'ph', value: '6.5' }],
    hazards: [],
    createdAt: '2026-07-12T13:00:00Z',
  },
  {
    id: 'seed-6',
    sessionId: 'session-seed-1',
    watershedId: 'lima-viana',
    catchmentId: '2121213820',
    position: [41.596, -8.606],
    sourceType: 'Dug well',
    readings: [{ measureId: 'nitrate', value: '25' }],
    hazards: [],
    createdAt: '2026-07-12T13:20:00Z',
  },
  {
    id: 'seed-7',
    sessionId: 'session-seed-1',
    watershedId: 'lima-viana',
    catchmentId: '2120019210',
    position: [41.5736, -8.7312],
    sourceType: 'Borehole',
    readings: [{ measureId: 'ph', value: '7' }],
    hazards: [],
    createdAt: '2026-07-12T13:40:00Z',
  },
  {
    id: 'seed-8',
    sessionId: 'session-mock-1',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.701, -8.788],
    sourceType: 'Dug well',
    readings: [{ measureId: 'nitrate', value: '10' }, { measureId: 'ph', value: '6.5' }],
    hazards: [],
    createdAt: '2026-03-18T11:20:00Z',
  },
  {
    id: 'seed-9',
    sessionId: 'session-mock-0',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-lima-lower',
    position: [41.712, -8.822],
    sourceType: 'Spring',
    readings: [{ measureId: 'ph', value: '7' }],
    hazards: ['eucalyptus'],
    createdAt: '2025-11-02T08:55:00Z',
  },
]

export const SEED_CHAT_THREADS = [
  {
    id: 'community-viana',
    kind: 'community',
    basinId: 'lima',
    townId: 'viana',
    subject: 'status',
    title: '',
    placeId: null,
    placeLabel: null,
    author: 'Sofia (moderator)',
    createdAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'thread-1',
    basinId: 'lima',
    townId: 'viana',
    subject: 'hazard-alert',
    title: 'Nitrate after rain',
    placeId: 'seed-1',
    placeLabel: 'Dug well',
    author: 'Tiago',
    createdAt: '2026-07-12T11:05:00Z',
  },
  {
    id: 'thread-2',
    basinId: 'lima',
    townId: 'viana',
    subject: 'status',
    title: 'Spring still clear',
    placeId: 'seed-2',
    placeLabel: 'Spring',
    author: 'Ana',
    createdAt: '2026-07-12T14:20:00Z',
  },
  {
    id: 'thread-3',
    basinId: 'lima',
    townId: 'viana',
    subject: 'investigation',
    title: 'Sample after rain',
    placeId: null,
    placeLabel: null,
    author: 'Sofia (moderator)',
    createdAt: '2026-07-11T09:00:00Z',
  },
  {
    id: 'thread-4',
    basinId: 'costeiras',
    townId: 'viana',
    subject: 'hazard-discuss',
    title: 'Eucalyptus near the coast',
    placeId: 'seed-3',
    placeLabel: 'Borehole',
    author: 'Marta',
    createdAt: '2026-07-10T08:30:00Z',
  },
]

export const SEED_CHAT_MESSAGES = [
  {
    id: 'msg-community-1',
    threadId: 'community-viana',
    author: 'Sofia (moderator)',
    text: 'This is the Viana do Castelo community chat. Use threads for one place or one hazard.',
    createdAt: '2026-07-10T08:00:00Z',
  },
  {
    id: 'msg-community-2',
    threadId: 'community-viana',
    author: 'Tiago',
    text: 'Logged a well near the mill this week. Nitrate still high after rain.',
    createdAt: '2026-07-12T10:40:00Z',
  },
  {
    id: 'msg-1',
    threadId: 'thread-3',
    author: 'Sofia (moderator)',
    text: 'Reminder: sample within a day or two of rain if you can — readings shift fast around here.',
    createdAt: '2026-07-11T09:00:00Z',
  },
  {
    id: 'msg-2',
    threadId: 'thread-1',
    author: 'Tiago',
    text: 'Well by the old mill tested high nitrate again today.',
    createdAt: '2026-07-12T11:05:00Z',
  },
  {
    id: 'msg-2b',
    threadId: 'thread-1',
    author: 'Ana',
    text: 'Same here after the rain — spring uphill looks fine though.',
    createdAt: '2026-07-12T14:20:00Z',
  },
  {
    id: 'msg-3',
    threadId: 'thread-2',
    author: 'Ana',
    text: 'Spring still tasting normal. pH 7 this morning.',
    createdAt: '2026-07-12T14:20:00Z',
  },
  {
    id: 'msg-4',
    threadId: 'thread-4',
    author: 'Marta',
    text: 'Anyone else seeing spray near the coastal borehole?',
    createdAt: '2026-07-10T08:30:00Z',
  },
]
