export const SEED_SAMPLES = [
  {
    id: 'seed-1',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.706, -8.79],
    sourceType: 'Dug well',
    readings: [{ measureId: 'nitrate', value: '100+' }, { measureId: 'ph', value: '5.5' }],
    hazards: [],
    usages: ['drinking', 'dishes', 'laundry'],
    createdAt: '2026-07-12T10:15:00Z',
  },
  {
    id: 'seed-2',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.685, -8.815],
    sourceType: 'Spring',
    readings: [{ measureId: 'nitrate', value: '0' }, { measureId: 'ph', value: '7' }],
    hazards: [],
    createdAt: '2026-07-12T11:02:00Z',
  },
  {
    id: 'seed-3',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-lima-lower',
    position: [41.72, -8.83],
    sourceType: 'Borehole',
    readings: [{ measureId: 'ph', value: '6.5' }],
    hazards: [],
    createdAt: '2026-07-12T11:40:00Z',
  },
  {
    id: 'seed-4',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.698, -8.802],
    sourceType: 'Mina (mine)',
    readings: [{ measureId: 'nitrate', value: '10' }],
    hazards: [],
    createdAt: '2026-07-12T12:10:00Z',
  },
  {
    id: 'seed-5',
    watershedId: 'lima-viana',
    catchmentId: '2121213570',
    position: [41.6236, -8.4912],
    sourceType: 'Spring',
    readings: [{ measureId: 'nitrate', value: '10' }, { measureId: 'ph', value: '6.5' }],
    hazards: [],
    createdAt: '2026-07-12T13:00:00Z',
  },
  {
    id: 'seed-6',
    watershedId: 'lima-viana',
    catchmentId: '2121213820',
    position: [41.596, -8.606],
    sourceType: 'Dug well',
    readings: [{ measureId: 'nitrate', value: '100+' }],
    hazards: [],
    createdAt: '2026-07-12T13:20:00Z',
  },
  {
    id: 'seed-7',
    watershedId: 'lima-viana',
    catchmentId: '2120019210',
    position: [41.5736, -8.7312],
    sourceType: 'Borehole',
    readings: [{ measureId: 'ph', value: '7' }],
    hazards: [],
    createdAt: '2026-07-12T13:40:00Z',
  },
  {
    id: 'seed-8',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-estoraos',
    position: [41.701, -8.788],
    sourceType: 'Dug well',
    readings: [{ measureId: 'nitrate', value: '10' }, { measureId: 'ph', value: '6.5' }],
    hazards: [],
    createdAt: '2026-03-18T11:20:00Z',
  },
  {
    id: 'seed-9',
    watershedId: 'lima-viana',
    catchmentId: 'catchment-lima-lower',
    position: [41.712, -8.822],
    sourceType: 'Spring',
    readings: [{ measureId: 'ph', value: '7' }],
    hazards: [],
    createdAt: '2025-11-02T08:55:00Z',
  },
]

export const SEED_HAZARDS = [
  { id: 'hazard-1', typeId: 'septic', activity: 'active', position: [41.709, -8.786], createdAt: '2026-07-12T10:20:00Z' },
  { id: 'hazard-2', typeId: 'agriculture', activity: 'passive', position: [41.702, -8.796], createdAt: '2026-07-12T10:21:00Z' },
  { id: 'hazard-3', typeId: 'eucalyptus', activity: 'passive', position: [41.715, -8.818], createdAt: '2025-11-02T08:56:00Z' },
]

export const SEED_THREADS = [
  { id: 'community-viana', kind: 'community', basinId: 'lima', townId: 'viana', subject: 'status', title: '', placeId: null, placeLabel: null, author: 'Sofia (moderator)', createdAt: '2026-07-10T08:00:00Z' },
  { id: 'thread-1', kind: 'topic', basinId: 'lima', townId: 'viana', subject: 'hazard-alert', title: 'Nitrate after rain', placeId: 'seed-1', placeLabel: 'Dug well', author: 'Tiago', createdAt: '2026-07-12T11:05:00Z' },
  { id: 'thread-2', kind: 'topic', basinId: 'lima', townId: 'viana', subject: 'status', title: 'Spring still clear', placeId: 'seed-2', placeLabel: 'Spring', author: 'Ana', createdAt: '2026-07-12T14:20:00Z' },
  { id: 'thread-3', kind: 'topic', basinId: 'lima', townId: 'viana', subject: 'investigation', title: 'Sample after rain', placeId: null, placeLabel: null, author: 'Sofia (moderator)', createdAt: '2026-07-11T09:00:00Z' },
  { id: 'thread-4', kind: 'topic', basinId: 'costeiras', townId: 'viana', subject: 'hazard-discuss', title: 'Eucalyptus near the coast', placeId: 'seed-3', placeLabel: 'Borehole', author: 'Marta', createdAt: '2026-07-10T08:30:00Z' },
]

export const SEED_MESSAGES = [
  { id: 'msg-community-1', threadId: 'community-viana', author: 'Sofia (moderator)', text: 'This is the Viana do Castelo community chat. Use threads for one place or one hazard.', createdAt: '2026-07-10T08:00:00Z' },
  { id: 'msg-community-2', threadId: 'community-viana', author: 'Tiago', text: 'Logged a well near the mill this week. Nitrate still high after rain.', createdAt: '2026-07-12T10:40:00Z' },
  { id: 'msg-1', threadId: 'thread-3', author: 'Sofia (moderator)', text: 'Reminder: sample within a day or two of rain if you can — readings shift fast around here.', createdAt: '2026-07-11T09:00:00Z' },
  { id: 'msg-2', threadId: 'thread-1', author: 'Tiago', text: 'Well by the old mill tested high nitrate again today.', createdAt: '2026-07-12T11:05:00Z' },
  { id: 'msg-2b', threadId: 'thread-1', author: 'Ana', text: 'Same here after the rain — spring uphill looks fine though.', createdAt: '2026-07-12T14:20:00Z' },
  { id: 'msg-3', threadId: 'thread-2', author: 'Ana', text: 'Spring still tasting normal. pH 7 this morning.', createdAt: '2026-07-12T14:20:00Z' },
  { id: 'msg-4', threadId: 'thread-4', author: 'Marta', text: 'Anyone else seeing spray near the coastal borehole?', createdAt: '2026-07-10T08:30:00Z' },
]
